import Head from "next/head";
import axios from "axios";
import { useState } from "react";
import { BsSearch } from "react-icons/bs";
import Spinner from '../components/Spinner';

export default function Home() {
  const [name, setName] = useState("");
  const [people, setPeople] = useState({});
  const [loading, setLoading] = useState(false);
  const url = "https://swapi.dev/api/people/1/";

  const fetchPeople = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setPeople(response.data);
      console.log(response.data);
    });
    setName("");
    setLoading(false);
  };
  if (loading) {
    return <Spinner />;
  } else {
    return (
      <div>
        <Head>
          <title>Swapi Challenge Get Wannabe</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      
            <button onClick={fetchPeople}>People</button>
      </div>
    );
  }
}
